name: Hackathon API â€“ Test & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create test .env
        run: |
          cat <<EOF > .env
          WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}

          POSTGRES_URL=${{ secrets.POSTGRES_URL }}
          MONGO_URL=${{ secrets.MONGO_URL }}
          MYSQL_URL=${{ secrets.MYSQL_URL }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME  }}
          EOF
      - name: Export test environment variables
        run: |
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV
          echo "MYSQL_URL=${{ secrets.MYSQL_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        run: pytest -q


  build_and_deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: github.actor == 'alxprgs'
    environment: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/alxprgs/zovnikovy_hackathon_22-23-11-25:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/alxprgs/zovnikovy_hackathon_22-23-11-25:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
            cd /srv/hackathon
            docker compose pull
            docker compose up -d
